"""Config module initialization"""
from .database import db, client
from .settings import (
    JWT_SECRET, JWT_ALGORITHM, JWT_EXPIRATION_DAYS,
    STRIPE_SECRET_KEY, STRIPE_PUBLISHABLE_KEY, STRIPE_WEBHOOK_SECRET,
    PLATFORM_FEE_PERCENT, RESEND_API_KEY,
    FEATURE_FLAGS, MARKETS_CONFIG, COUNTRY_TO_MARKET
)

__all__ = [
    'db', 'client',
    'JWT_SECRET', 'JWT_ALGORITHM', 'JWT_EXPIRATION_DAYS',
    'STRIPE_SECRET_KEY', 'STRIPE_PUBLISHABLE_KEY', 'STRIPE_WEBHOOK_SECRET',
    'PLATFORM_FEE_PERCENT', 'RESEND_API_KEY',
    'FEATURE_FLAGS', 'MARKETS_CONFIG', 'COUNTRY_TO_MARKET'
]
